#!/usr/bin/env python3
"""
Pair-aware targeted window encoding for retained pseudo-haplotype pairs.

This script consumes the output of ``src/filter_contig_pairs.py`` after
per-haplotype read alignment has been generated by
``src/align_cluster_reads_to_haps.py``. For each retained pair, it assigns reads
between the two haplotypes in memory, encodes only SV-focused 2kb windows, and
writes metadata describing which 200bp subwindows should be used for downstream
pair scoring.
"""

from __future__ import annotations

import argparse
import concurrent.futures
import csv
import shutil
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Mapping, Optional, Sequence, Tuple

import numpy as np
import pysam

from featurizers.extract_features import encode_records


@dataclass(frozen=True)
class SVInterval:
    """A contig-local SV interval parsed from the haplotype FASTA header."""

    sv_id: str
    start: int
    end: int


@dataclass(frozen=True)
class HaplotypeInfo:
    """Metadata for one retained haplotype."""

    hap_id: str
    gt: str
    contig_name: str
    length: int
    bam_path: Path
    sv_intervals: Tuple[SVInterval, ...]


@dataclass(frozen=True)
class PairInfo:
    """One retained haplotype pair."""

    rank: int
    pair_id: str
    hap1_id: str
    hap2_id: str


@dataclass
class HapAlignmentData:
    """Alignment records and assignment scores for one haplotype BAM."""

    records_by_read: Dict[str, List[pysam.AlignedSegment]]
    scores_by_read: Dict[str, int]


@dataclass
class AssignedPairRecords:
    """Read assignment results for one pair."""

    records_by_hap: Dict[str, List[pysam.AlignedSegment]]
    reads_assigned_hap1: Optional[int]
    reads_assigned_hap2: Optional[int]
    hap1_better: int
    hap2_better: int
    score_ties: int
    only_hap1: int
    only_hap2: int
    neither_aligned: int


@dataclass(frozen=True)
class TargetWindow:
    """One 2kb target window and its focused subwindow annotations."""

    start: int
    end: int
    focus_mask: Tuple[int, ...]
    sv_to_subwindows: Mapping[str, Tuple[int, ...]]


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""

    parser = argparse.ArgumentParser(
        description=(
            "Generate pair-aware targeted 2000bp x 9 alignment matrices for "
            "retained haplotype pairs. --threads controls cluster-level worker "
            "processes; each worker processes one cluster at a time."
        )
    )
    parser.add_argument(
        "cluster_dir",
        help="Directory containing per-cluster k-mer prefilter outputs.",
    )
    parser.add_argument(
        "--threads",
        type=int,
        default=1,
        help=(
            "Number of cluster-level workers to run in parallel. Each worker "
            "processes one cluster at a time. Default: 1."
        ),
    )
    parser.add_argument(
        "--cluster",
        action="append",
        default=None,
        help=(
            "Optional cluster name to process. May be supplied multiple times. "
            "Default: process all clusters under cluster_dir."
        ),
    )
    parser.add_argument(
        "--window-size",
        type=int,
        default=2000,
        help="Encoded window size in bp. Default: 2000.",
    )
    parser.add_argument(
        "--subwindow-size",
        type=int,
        default=200,
        help="Subwindow size for focus masks in bp. Default: 200.",
    )
    parser.add_argument(
        "--merge-distance",
        type=int,
        default=1800,
        help="Merge nearby SV intervals into one target group when the gap is <= this value. Default: 1800.",
    )
    parser.add_argument(
        "--long-group-stride",
        type=int,
        default=1000,
        help="Stride for tiling long target groups with overlapping windows. Default: 1000.",
    )
    parser.add_argument(
        "--hap-bam-subdir",
        default="hap_bams",
        help="Subdirectory containing per-haplotype BAMs. Default: hap_bams.",
    )
    parser.add_argument(
        "--output-subdir",
        default="pair_target_windows",
        help="Subdirectory created under each cluster for encoded pair windows. Default: pair_target_windows.",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Regenerate pair output directories even if windows.tsv already exists.",
    )
    parser.add_argument(
        "--no-assigned-depth-normalization",
        action="store_true",
        help=(
            "Disable non-self pair depth normalization. By default, each assigned "
            "haplotype matrix is scaled by total_assigned_reads / hap_assigned_reads "
            "to better match full-depth training matrices."
        ),
    )
    return parser.parse_args()


def read_tsv(
    path: Path,
) -> List[Dict[str, str]]:
    """Read a tab-delimited file into dictionaries."""

    with path.open("r", encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle, delimiter="\t"))


def write_tsv(
    path: Path,
    rows: Sequence[Mapping[str, object]],
    fields: Sequence[str],
) -> None:
    """Write dictionaries to a tab-delimited file."""

    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(
            handle, fieldnames=list(fields), delimiter="\t", lineterminator="\n"
        )
        writer.writeheader()
        for row in rows:
            writer.writerow({field: row.get(field, "") for field in fields})


def parse_bool(
    value: str,
) -> bool:
    """Parse TSV boolean text."""

    return value.lower() in {"1", "true", "t", "yes", "y"}


def parse_sv_intervals(
    contig_name: str,
) -> Tuple[SVInterval, ...]:
    """Parse ``SVs=sv_id:start-end;...`` intervals from a contig name."""

    fields = {}
    for item in contig_name.split("|"):
        if "=" not in item:
            continue
        key, value = item.split("=", 1)
        fields[key] = value

    sv_text = fields.get("SVs")
    if not sv_text:
        raise ValueError(f"Contig name does not contain SVs= metadata: {contig_name}")

    intervals: List[SVInterval] = []
    for entry in sv_text.split(";"):
        if not entry:
            continue
        try:
            sv_id, interval_text = entry.rsplit(":", 1)
            start_text, end_text = interval_text.split("-", 1)
            start = int(start_text)
            end = int(end_text)
        except ValueError as exc:
            raise ValueError(
                f"Could not parse SV interval entry {entry!r} in {contig_name!r}"
            ) from exc
        if start < 0 or end <= start:
            raise ValueError(f"Invalid SV interval {entry!r} in {contig_name!r}")
        intervals.append(SVInterval(sv_id=sv_id, start=start, end=end))

    if not intervals:
        raise ValueError(f"No SV intervals parsed from contig name: {contig_name}")

    return tuple(intervals)


def load_haplotypes(
    cluster_dir: Path,
    hap_bam_subdir: str,
) -> Dict[str, HaplotypeInfo]:
    """Load retained haplotype metadata for one cluster."""

    rows = read_tsv(cluster_dir / "retained_haplotypes.tsv")
    haplotypes: Dict[str, HaplotypeInfo] = {}
    for row in rows:
        hap_id = row["hap_id"]
        bam_path = cluster_dir / hap_bam_subdir / f"{hap_id}.bam"
        haplotypes[hap_id] = HaplotypeInfo(
            hap_id=hap_id,
            gt=row["gt"],
            contig_name=row["contig_name"],
            length=int(row["length"]),
            bam_path=bam_path,
            sv_intervals=parse_sv_intervals(row["contig_name"]),
        )

    return haplotypes


def load_retained_pairs(
    cluster_dir: Path,
) -> List[PairInfo]:
    """Load retained pairs from ``prefilter_pairs.tsv``."""

    pairs = []
    for row in read_tsv(cluster_dir / "prefilter_pairs.tsv"):
        if not parse_bool(row["retained"]):
            continue
        pairs.append(
            PairInfo(
                rank=int(row["rank"]),
                pair_id=row["pair_id"],
                hap1_id=row["hap1_id"],
                hap2_id=row["hap2_id"],
            )
        )

    return sorted(pairs, key=lambda pair: pair.rank)


def load_cluster_read_names(
    cluster_dir: Path,
) -> Tuple[str, ...]:
    """Load read names from ``cluster_reads.fasta`` for assignment QC."""

    read_names = []
    with (cluster_dir / "cluster_reads.fasta").open("r", encoding="utf-8") as handle:
        for line in handle:
            if line.startswith(">"):
                read_names.append(line[1:].strip().split()[0])
    return tuple(sorted(set(read_names)))


def cigar_aligned_query_bases(
    record: pysam.AlignedSegment,
) -> int:
    """Count query-consuming aligned CIGAR bases."""

    if not record.cigartuples:
        return 0
    return sum(length for op, length in record.cigartuples if op in (0, 1, 7, 8))


def cigar_clipped_bases(
    record: pysam.AlignedSegment,
) -> int:
    """Count soft/hard clipped CIGAR bases."""

    if not record.cigartuples:
        return 0
    return sum(length for op, length in record.cigartuples if op in (4, 5))


def score_record(
    record: pysam.AlignedSegment,
) -> int:
    """Score one alignment record for read assignment."""

    edit_distance = int(record.get_tag("NM")) if record.has_tag("NM") else 0
    return (
        cigar_aligned_query_bases(record)
        - 3 * edit_distance
        - cigar_clipped_bases(record)
    )


def load_hap_alignment_data(
    haplotype: HaplotypeInfo,
) -> HapAlignmentData:
    """Load primary and supplementary records from one haplotype BAM."""

    if not haplotype.bam_path.is_file():
        raise FileNotFoundError(f"Missing haplotype BAM: {haplotype.bam_path}")
    bai_path = Path(str(haplotype.bam_path) + ".bai")
    if not bai_path.is_file():
        raise FileNotFoundError(f"Missing haplotype BAM index: {bai_path}")

    records_by_read: Dict[str, List[pysam.AlignedSegment]] = defaultdict(list)
    with pysam.AlignmentFile(str(haplotype.bam_path), "rb") as bam:
        for record in bam.fetch(until_eof=True):
            if record.is_unmapped or record.is_secondary:
                continue
            if record.reference_name != haplotype.contig_name:
                continue
            records_by_read[record.query_name].append(record)

    scores_by_read = {
        read_name: sum(score_record(record) for record in records)
        for read_name, records in records_by_read.items()
    }

    return HapAlignmentData(
        records_by_read=dict(records_by_read), scores_by_read=scores_by_read
    )


def assign_pair_records(
    pair: PairInfo,
    hap1_data: HapAlignmentData,
    hap2_data: HapAlignmentData,
    all_read_names: Sequence[str],
) -> AssignedPairRecords:
    """Assign reads to the better haplotype for a non-self pair."""

    records_by_hap = {pair.hap1_id: [], pair.hap2_id: []}
    reads_assigned_hap1 = 0
    reads_assigned_hap2 = 0
    hap1_better = 0
    hap2_better = 0
    score_ties = 0
    only_hap1 = 0
    only_hap2 = 0
    neither_aligned = 0

    read_names = sorted(
        set(all_read_names)
        | set(hap1_data.records_by_read)
        | set(hap2_data.records_by_read)
    )
    for read_name in read_names:
        has_hap1 = read_name in hap1_data.records_by_read
        has_hap2 = read_name in hap2_data.records_by_read

        if has_hap1 and not has_hap2:
            only_hap1 += 1
            records_by_hap[pair.hap1_id].extend(hap1_data.records_by_read[read_name])
            reads_assigned_hap1 += 1
        elif has_hap2 and not has_hap1:
            only_hap2 += 1
            records_by_hap[pair.hap2_id].extend(hap2_data.records_by_read[read_name])
            reads_assigned_hap2 += 1
        elif has_hap1 and has_hap2:
            score1 = hap1_data.scores_by_read[read_name]
            score2 = hap2_data.scores_by_read[read_name]
            if score1 > score2:
                hap1_better += 1
                records_by_hap[pair.hap1_id].extend(
                    hap1_data.records_by_read[read_name]
                )
                reads_assigned_hap1 += 1
            elif score2 > score1:
                hap2_better += 1
                records_by_hap[pair.hap2_id].extend(
                    hap2_data.records_by_read[read_name]
                )
                reads_assigned_hap2 += 1
            else:
                score_ties += 1
                if reads_assigned_hap1 <= reads_assigned_hap2:
                    records_by_hap[pair.hap1_id].extend(
                        hap1_data.records_by_read[read_name]
                    )
                    reads_assigned_hap1 += 1
                else:
                    records_by_hap[pair.hap2_id].extend(
                        hap2_data.records_by_read[read_name]
                    )
                    reads_assigned_hap2 += 1
        else:
            neither_aligned += 1

    return AssignedPairRecords(
        records_by_hap=records_by_hap,
        reads_assigned_hap1=reads_assigned_hap1,
        reads_assigned_hap2=reads_assigned_hap2,
        hap1_better=hap1_better,
        hap2_better=hap2_better,
        score_ties=score_ties,
        only_hap1=only_hap1,
        only_hap2=only_hap2,
        neither_aligned=neither_aligned,
    )


def self_pair_records(
    pair: PairInfo,
    hap_data: HapAlignmentData,
) -> AssignedPairRecords:
    """Return all records for a self pair without read assignment."""

    all_records = [
        record for records in hap_data.records_by_read.values() for record in records
    ]
    return AssignedPairRecords(
        records_by_hap={pair.hap1_id: all_records},
        reads_assigned_hap1=None,
        reads_assigned_hap2=None,
        hap1_better=0,
        hap2_better=0,
        score_ties=0,
        only_hap1=0,
        only_hap2=0,
        neither_aligned=0,
    )


def clamp_window_start(
    start: int,
    contig_length: int,
    window_size: int,
) -> int:
    """Clamp a window start while preserving fixed window length."""

    return min(max(0, start), contig_length - window_size)


def group_sv_intervals(
    intervals: Sequence[SVInterval],
    merge_distance: int,
) -> List[List[SVInterval]]:
    """Merge nearby SV intervals into target groups."""

    sorted_intervals = sorted(
        intervals, key=lambda interval: (interval.start, interval.end, interval.sv_id)
    )
    groups: List[List[SVInterval]] = []
    current: List[SVInterval] = []
    current_end: Optional[int] = None

    for interval in sorted_intervals:
        if not current:
            current = [interval]
            current_end = interval.end
            continue
        assert current_end is not None
        if interval.start - current_end <= merge_distance:
            current.append(interval)
            current_end = max(current_end, interval.end)
        else:
            groups.append(current)
            current = [interval]
            current_end = interval.end

    if current:
        groups.append(current)

    return groups


def candidate_window_starts(
    group: Sequence[SVInterval],
    contig_length: int,
    window_size: int,
    stride: int,
) -> List[int]:
    """Generate fixed-length window starts for one SV group."""

    if contig_length < window_size:
        return []

    group_start = min(interval.start for interval in group)
    group_end = max(interval.end for interval in group)
    group_span = group_end - group_start

    if group_span <= window_size:
        center = (group_start + group_end) // 2
        return [
            clamp_window_start(center - window_size // 2, contig_length, window_size)
        ]

    target_start = max(0, group_start - window_size // 2)
    target_end = min(contig_length, group_end + window_size // 2)
    final_start = clamp_window_start(
        target_end - window_size, contig_length, window_size
    )

    starts = []
    start = clamp_window_start(target_start, contig_length, window_size)
    while start < final_start:
        starts.append(start)
        start += stride
    starts.append(final_start)

    return sorted(set(starts))


def build_target_windows(
    intervals: Sequence[SVInterval],
    contig_length: int,
    window_size: int,
    subwindow_size: int,
    merge_distance: int,
    long_group_stride: int,
) -> List[TargetWindow]:
    """Create target windows and focus annotations for a haplotype."""

    if window_size % subwindow_size != 0:
        raise ValueError("--window-size must be divisible by --subwindow-size")

    starts = set()
    for group in group_sv_intervals(intervals, merge_distance):
        starts.update(
            candidate_window_starts(
                group, contig_length, window_size, long_group_stride
            )
        )

    windows = []
    subwindow_count = window_size // subwindow_size
    for start in sorted(starts):
        end = start + window_size
        focus_mask = [0] * subwindow_count
        sv_to_subwindows: Dict[str, List[int]] = defaultdict(list)
        for interval in intervals:
            focused_indices = []
            for index in range(subwindow_count):
                sub_start = start + index * subwindow_size
                sub_end = sub_start + subwindow_size
                if sub_end > interval.start and sub_start < interval.end:
                    focused_indices.append(index)

            if interval.end - interval.start == 1 and focused_indices:
                anchor_index = focused_indices[0]
                if anchor_index > 0:
                    focused_indices.append(anchor_index - 1)

            for index in sorted(set(focused_indices)):
                focus_mask[index] = 1
                sv_to_subwindows[interval.sv_id].append(index)

        if any(focus_mask):
            windows.append(
                TargetWindow(
                    start=start,
                    end=end,
                    focus_mask=tuple(focus_mask),
                    sv_to_subwindows={
                        sv_id: tuple(sorted(set(indices)))
                        for sv_id, indices in sv_to_subwindows.items()
                    },
                )
            )

    return windows


def safe_pair_dir_name(
    pair: PairInfo,
) -> str:
    """Return a stable pair directory name."""

    return f"{pair.rank:02d}_{pair.hap1_id}__{pair.hap2_id}"


def scale_count_depth_channels(
    feature: np.ndarray,
    scale: float,
) -> np.ndarray:
    """Scale log-normalized count/depth channels by a positive factor."""

    if scale <= 0:
        raise ValueError("Depth normalization scale must be positive")
    if scale == 1:
        return feature

    scaled = feature.copy()
    count_channels = (0, 1, 2, 3, 8)
    for channel in count_channels:
        raw_values = np.expm1(scaled[:, channel])
        scaled[:, channel] = np.log1p(raw_values * scale)
    return scaled


def assigned_depth_scales(
    pair: PairInfo,
    assigned: AssignedPairRecords,
    normalize: bool,
) -> Dict[str, float]:
    """Return per-haplotype depth scaling factors for one assigned pair."""

    if not normalize or pair.hap1_id == pair.hap2_id:
        return {pair.hap1_id: 1.0}
    if assigned.reads_assigned_hap1 is None or assigned.reads_assigned_hap2 is None:
        return {pair.hap1_id: 1.0, pair.hap2_id: 1.0}

    hap1_count = assigned.reads_assigned_hap1
    hap2_count = assigned.reads_assigned_hap2
    total = hap1_count + hap2_count
    if total <= 0:
        return {pair.hap1_id: 1.0, pair.hap2_id: 1.0}

    return {
        pair.hap1_id: total / hap1_count if hap1_count > 0 else 1.0,
        pair.hap2_id: total / hap2_count if hap2_count > 0 else 1.0,
    }


def encode_pair_windows(
    cluster_name: str,
    pair: PairInfo,
    haplotypes: Mapping[str, HaplotypeInfo],
    assigned: AssignedPairRecords,
    pair_dir: Path,
    window_size: int,
    subwindow_size: int,
    merge_distance: int,
    long_group_stride: int,
    normalize_assigned_depth: bool,
) -> Tuple[List[Dict[str, object]], List[Dict[str, object]]]:
    """Encode all target windows for one pair."""

    feature_dir = pair_dir / "features"
    feature_dir.mkdir(parents=True, exist_ok=True)

    window_rows: List[Dict[str, object]] = []
    focus_rows: List[Dict[str, object]] = []
    hap_ids = (
        [pair.hap1_id] if pair.hap1_id == pair.hap2_id else [pair.hap1_id, pair.hap2_id]
    )
    depth_scales = assigned_depth_scales(pair, assigned, normalize_assigned_depth)

    for hap_id in hap_ids:
        hap = haplotypes[hap_id]
        records = assigned.records_by_hap.get(hap_id, [])
        depth_scale = depth_scales.get(hap_id, 1.0)
        target_windows = build_target_windows(
            hap.sv_intervals,
            hap.length,
            window_size,
            subwindow_size,
            merge_distance,
            long_group_stride,
        )

        for window in target_windows:
            feature = encode_records(
                records, window.start, window.end, contig=hap.contig_name
            )
            feature = scale_count_depth_channels(feature, depth_scale)
            feature_name = f"{hap_id}_{window.start}_{window.end}.npy"
            feature_path = feature_dir / feature_name
            np.save(feature_path, feature)

            overlap_sv_ids = sorted(window.sv_to_subwindows)
            window_rows.append(
                {
                    "feature_path": str(feature_path.relative_to(pair_dir)),
                    "cluster": cluster_name,
                    "pair_rank": pair.rank,
                    "pair_id": pair.pair_id,
                    "hap_id": hap_id,
                    "contig_name": hap.contig_name,
                    "bam_path": str(hap.bam_path),
                    "window_start": window.start,
                    "window_end": window.end,
                    "focus_mask": ",".join(str(value) for value in window.focus_mask),
                    "overlap_sv_ids": ";".join(overlap_sv_ids),
                    "num_records_encoded": len(records),
                    "depth_scale": f"{depth_scale:.6f}",
                    "self_pair": str(pair.hap1_id == pair.hap2_id).lower(),
                }
            )

            for sv_id, subwindow_indices in window.sv_to_subwindows.items():
                for subwindow_index in subwindow_indices:
                    subwindow_start = window.start + subwindow_index * subwindow_size
                    focus_rows.append(
                        {
                            "feature_path": str(feature_path.relative_to(pair_dir)),
                            "cluster": cluster_name,
                            "pair_rank": pair.rank,
                            "pair_id": pair.pair_id,
                            "hap_id": hap_id,
                            "sv_id": sv_id,
                            "window_start": window.start,
                            "window_end": window.end,
                            "subwindow_index": subwindow_index,
                            "subwindow_start": subwindow_start,
                            "subwindow_end": subwindow_start + subwindow_size,
                        }
                    )

    return window_rows, focus_rows


def process_cluster(
    cluster_dir: Path,
    args: argparse.Namespace,
) -> Dict[str, object]:
    """Process one cluster directory."""

    haplotypes = load_haplotypes(cluster_dir, args.hap_bam_subdir)
    pairs = load_retained_pairs(cluster_dir)
    cluster_read_names = load_cluster_read_names(cluster_dir)
    output_root = cluster_dir / args.output_subdir
    output_root.mkdir(parents=True, exist_ok=True)

    required_haps = sorted(
        {hap_id for pair in pairs for hap_id in (pair.hap1_id, pair.hap2_id)}
    )
    missing_haps = [hap_id for hap_id in required_haps if hap_id not in haplotypes]
    if missing_haps:
        raise ValueError(
            f"{cluster_dir.name}: retained pairs reference missing haplotypes: {missing_haps}"
        )

    pair_count = 0
    feature_count = 0
    skipped_pairs = 0
    for pair in pairs:
        pair_dir = output_root / safe_pair_dir_name(pair)
        if not args.overwrite and (pair_dir / "windows.tsv").is_file():
            skipped_pairs += 1
            continue
        if pair_dir.exists():
            shutil.rmtree(pair_dir)
        pair_dir.mkdir(parents=True, exist_ok=True)

        if pair.hap1_id == pair.hap2_id:
            hap_data = load_hap_alignment_data(haplotypes[pair.hap1_id])
            assigned = self_pair_records(pair, hap_data)
        else:
            hap1_data = load_hap_alignment_data(haplotypes[pair.hap1_id])
            hap2_data = load_hap_alignment_data(haplotypes[pair.hap2_id])
            assigned = assign_pair_records(
                pair,
                hap1_data,
                hap2_data,
                cluster_read_names,
            )

        window_rows, focus_rows = encode_pair_windows(
            cluster_dir.name,
            pair,
            haplotypes,
            assigned,
            pair_dir,
            args.window_size,
            args.subwindow_size,
            args.merge_distance,
            args.long_group_stride,
            not args.no_assigned_depth_normalization,
        )
        write_tsv(
            pair_dir / "windows.tsv",
            window_rows,
            fields=(
                "feature_path",
                "cluster",
                "pair_rank",
                "pair_id",
                "hap_id",
                "contig_name",
                "bam_path",
                "window_start",
                "window_end",
                "focus_mask",
                "overlap_sv_ids",
                "num_records_encoded",
                "depth_scale",
                "self_pair",
            ),
        )
        write_tsv(
            pair_dir / "focus_subwindows.tsv",
            focus_rows,
            fields=(
                "feature_path",
                "cluster",
                "pair_rank",
                "pair_id",
                "hap_id",
                "sv_id",
                "window_start",
                "window_end",
                "subwindow_index",
                "subwindow_start",
                "subwindow_end",
            ),
        )
        write_tsv(
            pair_dir / "assignment_summary.tsv",
            [
                {
                    "cluster": cluster_dir.name,
                    "pair_rank": pair.rank,
                    "pair_id": pair.pair_id,
                    "hap1_id": pair.hap1_id,
                    "hap2_id": pair.hap2_id,
                    "self_pair": str(pair.hap1_id == pair.hap2_id).lower(),
                    "reads_assigned_hap1": "NA"
                    if assigned.reads_assigned_hap1 is None
                    else assigned.reads_assigned_hap1,
                    "reads_assigned_hap2": "NA"
                    if assigned.reads_assigned_hap2 is None
                    else assigned.reads_assigned_hap2,
                    "hap1_better": assigned.hap1_better,
                    "hap2_better": assigned.hap2_better,
                    "score_ties": assigned.score_ties,
                    "only_hap1": assigned.only_hap1,
                    "only_hap2": assigned.only_hap2,
                    "neither_aligned": assigned.neither_aligned,
                }
            ],
            fields=(
                "cluster",
                "pair_rank",
                "pair_id",
                "hap1_id",
                "hap2_id",
                "self_pair",
                "reads_assigned_hap1",
                "reads_assigned_hap2",
                "hap1_better",
                "hap2_better",
                "score_ties",
                "only_hap1",
                "only_hap2",
                "neither_aligned",
            ),
        )
        pair_count += 1
        feature_count += len(window_rows)

    return {
        "cluster": cluster_dir.name,
        "pairs_processed": pair_count,
        "pairs_skipped": skipped_pairs,
        "features_written": feature_count,
    }


def discover_cluster_dirs(
    root: Path,
    selected_clusters: Optional[Sequence[str]],
) -> List[Path]:
    """Find cluster directories with required input files."""

    selected = set(selected_clusters) if selected_clusters else None
    clusters = []
    for path in sorted(root.iterdir()):
        if selected is not None and path.name not in selected:
            continue
        if not path.is_dir():
            continue
        if (path / "prefilter_pairs.tsv").is_file() and (
            path / "retained_haplotypes.tsv"
        ).is_file():
            clusters.append(path)

    if selected is not None:
        found = {path.name for path in clusters}
        missing = sorted(selected - found)
        if missing:
            raise FileNotFoundError(
                f"Requested clusters were not found or lack required TSVs: {missing}"
            )

    return clusters


def run_clusters(
    cluster_dirs: Sequence[Path],
    args: argparse.Namespace,
) -> List[Dict[str, object]]:
    """Run cluster processing serially or in parallel."""

    if args.threads == 1:
        return [process_cluster(cluster_dir, args) for cluster_dir in cluster_dirs]

    results = []
    with concurrent.futures.ProcessPoolExecutor(max_workers=args.threads) as executor:
        future_to_cluster = {
            executor.submit(process_cluster, cluster_dir, args): cluster_dir
            for cluster_dir in cluster_dirs
        }
        for future in concurrent.futures.as_completed(future_to_cluster):
            results.append(future.result())

    return results


def main() -> None:
    """Entry point."""

    args = parse_args()
    if args.threads < 1:
        raise ValueError("--threads must be at least 1")
    if args.window_size <= 0 or args.subwindow_size <= 0:
        raise ValueError("--window-size and --subwindow-size must be positive")
    if args.window_size % args.subwindow_size != 0:
        raise ValueError("--window-size must be divisible by --subwindow-size")
    if args.long_group_stride <= 0:
        raise ValueError("--long-group-stride must be positive")

    cluster_root = Path(args.cluster_dir).resolve()
    cluster_dirs = discover_cluster_dirs(cluster_root, args.cluster)
    print(f"Cluster root: {cluster_root}")
    print(f"Clusters: {len(cluster_dirs)}")
    print(f"Cluster-level threads: {args.threads}")
    print(f"Assigned-depth normalization: {not args.no_assigned_depth_normalization}")

    if not cluster_dirs:
        print("No clusters found.")
        return

    results = run_clusters(cluster_dirs, args)
    for result in sorted(results, key=lambda item: item["cluster"]):
        print(
            "{cluster}: pairs_processed={pairs_processed} "
            "pairs_skipped={pairs_skipped} features_written={features_written}".format(
                **result
            )
        )


if __name__ == "__main__":
    main()
